version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      #- ./app/:/home/app/
      - data:/var/lib/postgresql/data
    depends_on:
      - db
    networks:
      - mynet
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432

volumes:
  data:
networks:
  mynet: